version: '3'

services:
  pg_15:
    image: postgres:15
    ports:
      - "5415:5432"
    environment: &env
      POSTGRES_PASSWORD: passw0rd
    command: &cmd
      - postgres
#      - -c
#      - log_statement=all
#      - -c
#      - log_destination=stderr
#      - -c
#      - log_min_messages=DEBUG5
#      - -c
#      - log_min_error_statement=debug1

  timescale_pg_15:
    image: timescale/timescaledb-ha:pg15
    ports:
      - "5515:5432"
    environment: *env
    command: *cmd

  pg_14:
    image: postgres:14
    ports:
      - "5414:5432"
    environment: *env
    command: *cmd

  pg_13:
    image: postgres:13
    ports:
      - "5413:5432"
    environment: *env
    command: *cmd

  pg_12:
    image: postgres:12
    ports:
      - "5412:5432"
    environment: *env
    command: *cmd

  pg_16:
    image: postgres:16
    ports:
      - "5416:5432"
    environment: *env
    command: *cmd

  timescale_pg_16:
    image: timescale/timescaledb-ha:pg16
    ports:
      - "5516:5432"
    environment: *env
    command: *cmd
