version: '3'

services:
  pg_15:
    image: docker.io/library/postgres:15
    ports:
      - "5415:5432"
    environment: &env
      POSTGRES_PASSWORD: passw0rd
    command: &cmd
      - postgres
#      - -c
#      - log_statement=all
#      - -c
#      - log_destination=stderr
#      - -c
#      - log_min_messages=DEBUG5
#      - -c
#      - log_min_error_statement=debug1

  timescale_pg_15:
    image: docker.io/timescale/timescaledb-ha:pg15
    ports:
      - "5515:5432"
    environment: *env
    command: *cmd

  pg_14:
    image: docker.io/library/postgres:14
    ports:
      - "5414:5432"
    environment: *env
    command: *cmd

  pg_13:
    image: docker.io/library/postgres:13
    ports:
      - "5413:5432"
    environment: *env
    command: *cmd

  pg_12:
    image: docker.io/library/postgres:12
    ports:
      - "5412:5432"
    environment: *env
    command: *cmd

  pg_16:
    image: docker.io/library/postgres:16
    ports:
      - "5416:5432"
    environment: *env
    command: *cmd

  pg_17:
    image: docker.io/library/postgres:17
    ports:
      - "5417:5432"
    environment: *env
    command: *cmd

  timescale_pg_16:
    image: docker.io/timescale/timescaledb-ha:pg16
    ports:
      - "5516:5432"
    environment: *env
    command: *cmd

  timescale_pg_17:
    image: docker.io/timescale/timescaledb-ha:pg17
    ports:
      - "5517:5432"
    environment: *env
    command: *cmd

  pg_15_cleartext_auth:
    image: docker.io/library/postgres:15
    ports:
      - "5601:5432"
    environment:
      <<: *env
      POSTGRES_HOST_AUTH_METHOD: password
    command: *cmd

  pg_15_trust_auth:
    image: docker.io/library/postgres:15
    ports:
      - "5602:5432"
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_HOST_AUTH_METHOD: trust
    command: *cmd

  pg_15_ssl:
    image: docker.io/library/postgres:15
    ports:
      - "5603:5432"
    environment: *env
    entrypoint:
      - bash
      - -c
      - |
        cp /tmp/server.key /var/lib/postgresql/server.key
        chmod 600 /var/lib/postgresql/server.key
        chown postgres:postgres /var/lib/postgresql/server.key
        exec docker-entrypoint.sh postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      - ./test-certs/server.crt:/var/lib/postgresql/server.crt:ro
      - ./test-certs/server.key:/tmp/server.key:ro
