version: '3'

services:
  pg_15:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: passw0rd
    command: &cmd
      - postgres
      - -c
      - log_statement=all
      - -c
      - log_destination=stderr
      - -c
      - log_min_messages=info
      - -c
      - log_min_error_statement=debug1

  pg_14:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: passw0rd
    command: *cmd
