version: '3'

services:
  pg_15:
    image: postgres:15
    ports:
      - "5415:5432"
    environment: &env
      POSTGRES_PASSWORD: passw0rd
    command: &cmd
      - postgres
#      - -c
#      - log_statement=all
#      - -c
#      - log_destination=stderr
#      - -c
#      - log_min_messages=info
#      - -c
#      - log_min_error_statement=debug1

  timescale_pg_15:
    image: timescale/timescaledb-ha:pg15
    ports:
      - "5515:5432"
    environment: *env
    command: *cmd

  pg_14:
    image: postgres:14
    ports:
      - "5414:5432"
    environment: *env
    command: *cmd

  pg_13:
    image: postgres:13
    ports:
      - "5413:5432"
    environment: *env
    command: *cmd

  pg_12:
    image: postgres:12
    ports:
      - "5412:5432"
    environment: *env
    command: *cmd

  pg_16:
    image: postgres:16
    ports:
      - "5416:5432"
    environment: *env
    command: *cmd

  timescale_pg_16:
    image: timescale/timescaledb-ha:pg16
    ports:
      - "5516:5432"
    environment: *env
    command: *cmd

  pg_bouncer_backend:
    image: postgres:15
    environment: *env
    command: *cmd

  pg_bouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=passw0rd
      - DB_HOST=pg_bouncer_backend
      - AUTH_TYPE=scram-sha-256
      - POOL_MODE=transaction
      - ADMIN_USERS=postgres,dbuser
      - MAX_PREPARED_STATEMENTS=100
#      - IGNORE_STARTUP_PARAMETERS=search_path
      - TRACK_EXTRA_PARAMETERS=search_path
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
    ports:
      - "6415:5432"
    depends_on:
      - pg_bouncer_backend
