[package]
name = "elefant-client"
version = "0.1.0"
edition = "2021"
description = "A pure rust implementation of a postgres client that is independent of the executor runtime"
license = "MIT"

[dependencies]
futures = { workspace = true, optional = true }
tokio = { workspace = true, features = ["net", "io-util"], optional = true }
rand = { workspace = true }
base64 = { workspace = true }
hmac = { workspace = true }
md-5 = { workspace = true }
sha2 = { workspace = true }
stringprep = { workspace = true }
time = { workspace = true, features = ["formatting", "parsing"], optional = true }
uuid = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
rust_decimal = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
tracing = { workspace = true }
elefant-client-macros = { workspace = true, optional = true }
rustls = { workspace = true, optional = true, features = ["std"] }
rustls-pki-types = { workspace = true, optional = true }
x509-cert = { workspace = true, optional = true }
der = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
time = { workspace = true, features = ["macros"] }
rustls = { workspace = true, features = ["aws_lc_rs"] }
uuid = { workspace = true, features = ["v4"] }

[features]
tokio = ["dep:tokio", "futures"]
futures = ["dep:futures"]
time = ["dep:time"]
uuid = ["dep:uuid"]
json = ["dep:serde_json"]
decimal = ["dep:rust_decimal"]
pg_interval = []
serde = ["dep:serde"]
derive = ["dep:elefant-client-macros"]
rustls = ["dep:rustls", "dep:rustls-pki-types", "dep:x509-cert", "dep:der"]
