[package]
name = "compare-with-tokio-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["full"] }
tokio-postgres = { workspace = true }
elefant-client = { workspace = true, features = ["tokio"] }
futures = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }

[[bench]]
name = "binary_copy"
harness = false
