[package]
name = "elefant-tools"
version = "0.0.7"
edition = "2021"
license = "MIT"
repository = "https://github.com/zlepper/elefant-tools"
authors = ["Zlepper"]
description = "A library for doing things like pg_dump and pg_restore, with extra features, and probably more bugs."
readme = "../readme.md"
keywords = ["pg_dump", "pg_restore", "postgres", "backup", "restore"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true, features = ["rt", "fs"] }
elefant-client = { workspace = true, features = ["tokio", "pg_interval", "serde"] }
thiserror = { workspace = true }
itertools = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
ordered-float = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }
serde = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }
uuid = { workspace = true, features = ["fast-rng", "v4"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
similar-asserts = { workspace = true }
tracing-subscriber = { workspace = true }
elefant-test-macros = { workspace = true }

[features]
test_utilities = []
