[package]
name = "elefant-sync"
version = "0.0.7"
edition = "2021"
license = "MIT"
repository = "https://github.com/zlepper/elefant-tools"
authors = ["Zlepper"]
description = "A tool like pg_dump and pg_restore, but with extra features, and probably more bugs."
readme = "../readme.md"
keywords = ["pg_dump", "pg_restore", "postgres", "backup", "restore"]

[dependencies]
clap = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "fs"] }
elefant-tools = { workspace = true }
elefant-client = { workspace = true, features = ["tokio"] }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
elefant-test-macros = { workspace = true }
elefant-tools = { workspace = true, features = ["test_utilities"] }
